coverage:
  range: 0..22
  status:
    project:
      default: false
      tests:
        target: 100%
        paths:
          - 'tests/'
      app:
        target: 39%
        paths:
          - 'app/'
    patch: off
comment: off
codecov:
  disable_default_path_fixes: true
