ignore:
  - 'vendor/*'
  - 'node_modules/*'
  - 'public_html/vendor/*'
  - 'public_html/src/node_modules/*'
  - 'public_html/libraries/*'

coverage:
  range: 0..22
  status:
    project:
      default: false
      tests:
        target: 97%
        paths:
          - 'tests/'
      app:
        target: 0.5%
        paths:
          - 'app/'
    patch: off

comment: off
