fixes:
  - '/var/www/html/::/'
  - 'var/www/html/::'

ignore:
  - 'vendor/*'
  - 'node_modules/*'
  - 'public_html/vendor/*'
  - 'public_html/src/node_modules/*'
  - 'public_html/libraries/*'
  - '/var/www/html/vendor/*'
  - '/var/www/html/node_modules/*'
  - '/var/www/html/public_html/vendor/*'
  - '/var/www/html/public_html/src/node_modules/*'
  - '/var/www/html/public_html/libraries/*'

coverage:
  range: 0..22
  status:
    project:
      default: false
      tests:
        target: 100%
        paths:
          - 'tests/'
      app:
        target: 39%
        paths:
          - 'app/'
    patch: off
comment: off
