name: PHP actions

on: [push, pull_request]

jobs:
  php-7-3:
    name: Composer
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-7.3-${{ hashFiles('**/composer.lock') }}

    - name: Install dependencies PHP 7.3
    - uses: php-actions/composer@v5
      with:
        php-version: 7.3
        coverage: none
        extensions: intl

  php-7-4:
    name: Composer
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-7.4-${{ hashFiles('**/composer.lock') }}

    - name: Install dependencies PHP 7.4
    - uses: php-actions/composer@v5
      with:
        php-version: 7.4
        coverage: none
        extensions: intl

  php-8-0:
    name: Composer
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-8.0-${{ hashFiles('**/composer.lock') }}

    - name: Install dependencies PHP 8.0
    - uses: php-actions/composer@v5
      with:
        php-version: 8.0
        coverage: none
        extensions: intl

  code:
    name: Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PHP VarDump Check Action
        uses: umutphp/php-var-dump-check-action@v1
        with:
         exclude: 'vendor,tests'

      - name: Check PHP syntax errors
        uses: overtrue/phplint@2.3.5

      - name: DevSkim
        uses: microsoft/DevSkim-Action@v1

  security:
    name: Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PHP Security Checker
        uses: StephaneBour/actions-php-security-checker@1.1
        with:
          composer-lock: './composer.lock'
