name: Tests

on: [push, pull_request]

jobs:
  tests73:
    runs-on: ubuntu-latest
    name: PHP 7.3
    steps:
    - uses: actions/checkout@v2

    - name: Tests
      uses: YetiForceCompany/YetiForceCRM-Tests/7.3@main
      env:
        YETI_TEST_MODULE_KEY: ${{ secrets.YETI_TEST_MODULE_KEY }}

  tests74:
    runs-on: ubuntu-latest
    name: PHP 7.4
    steps:
    - uses: actions/checkout@v2

    - name: Tests
      uses: YetiForceCompany/YetiForceCRM-Tests/7.4@main
      env:
        YETI_TEST_MODULE_KEY: ${{ secrets.YETI_TEST_MODULE_KEY }}

  tests80:
    runs-on: ubuntu-latest
    name: PHP 8.0
    steps:
    - uses: actions/checkout@v2

    - name: Tests
      uses: YetiForceCompany/YetiForceCRM-Tests/8.0@main
      env:
        YETI_TEST_MODULE_KEY: ${{ secrets.YETI_TEST_MODULE_KEY }}
