name: Tests

on: [push, pull_request]

jobs:
  tests73:
    runs-on: ubuntu-latest
    name: PHP 7.3 - MariaDB 10.x
    steps:
    - uses: actions/checkout@v2

    - name: Tests
      uses: YetiForceCompany/YetiForceCRM-Tests/7.3@main
      env:
        YETI_TEST_MODULE_KEY: ${{ secrets.YETI_TEST_MODULE_KEY }}
        YETI_MAIL_PASS: ${{ secrets.YETI_MAIL_PASS }}

  tests74:
    runs-on: ubuntu-latest
    name: PHP 7.4 - MariaDB 10.x, xdebug , coverage
    steps:
    - uses: actions/checkout@v2

    - name: Tests
      uses: YetiForceCompany/YetiForceCRM-Tests/7.4@main
      env:
        YETI_TEST_MODULE_KEY: ${{ secrets.YETI_TEST_MODULE_KEY }}
        YETI_MAIL_PASS: ${{ secrets.YETI_MAIL_PASS }}

  tests80:
    runs-on: ubuntu-latest
    name: PHP 8.0 - MariaDB 10.x
    steps:
    - uses: actions/checkout@v2

    - name: Tests
      uses: YetiForceCompany/YetiForceCRM-Tests/8.0@main
      env:
        YETI_TEST_MODULE_KEY: ${{ secrets.YETI_TEST_MODULE_KEY }}
        YETI_MAIL_PASS: ${{ secrets.YETI_MAIL_PASS }}

  tests74MySQL57:
    runs-on: ubuntu-latest
    name: PHP 7.4 - Percona MySQL 5.7
    steps:
    - uses: actions/checkout@v2

    - name: Tests
      uses: YetiForceCompany/YetiForceCRM-Tests/percona-mysql-5.7@main
      env:
        YETI_TEST_MODULE_KEY: ${{ secrets.YETI_TEST_MODULE_KEY }}
        YETI_MAIL_PASS: ${{ secrets.YETI_MAIL_PASS }}

  tests74MySQL80:
    runs-on: ubuntu-latest
    name: PHP 7.4 - Percona MySQL 8.0
    steps:
    - uses: actions/checkout@v2

    - name: Tests
      uses: YetiForceCompany/YetiForceCRM-Tests/percona-mysql-8.0@main
      env:
        YETI_TEST_MODULE_KEY: ${{ secrets.YETI_TEST_MODULE_KEY }}
        YETI_MAIL_PASS: ${{ secrets.YETI_MAIL_PASS }}
